{{- if gt (.Values.worker.replicas | default 0) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ai-app
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        airs/session-source: "worker"
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRS_BASE_URL
              value: "{{ .Values.airs.baseUrl }}"
            - name: MODEL
              value: "{{ .Values.model.name }}"
          ports:
            - containerPort: 8001
{{- end }}
