apiVersion: v1
kind: Namespace
metadata:
  name: ai-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-rag
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-security
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
